### ISSUE TITLE
Write Central Algorithm

### ISSUE THREAD

**Issue by armsnyder** [eecs394-spr15/StockMyBar#11]
Write the central algorithm that takes what the user has in his/her bar, interfaces with the recipes service, and returns some combination of the ingredients the user should purchase and the resulting drinks they will be able to make with these new ingredients.

**Comment by armsnyder** [comment]
@YuxuanHe @missfxhr You guys should check out https://www.parse.com/docs/cloud_code_guide which describes how to write backend code using Parse. Use Josh's account.

**Comment by jpr71** [comment]
My email is joshuaroberts2016@u.northwestern.edu mailto:joshuaroberts2016@u.northwestern.edu 
the password: stockmybar

**Comment by armsnyder** [comment]
Josh and I will not be making the database service object like we said because there is no need. Both the algorithm and the database will exist on the same backend server, and Parse has completely automated the application interface.

**Comment by missfxhr** [comment]
Okay no problem. Will do it today.

**Comment by YuxuanHe** [comment]
Thank you, we will do it.

**Comment by missfxhr** [comment]
We finished our central algorithm version 0.1 just now. The function is "search4Recipe()". The input is a list of ingred names, like ["coffee", "milk"]. The output is a list of recipes, like [r1, r2], where ri is a part object, which, I believe, is also a js object in json format.

**Comment by missfxhr** [comment]
So when controller call our function using javascripts, it needs to use Parse.Cloud object and first connect to our parse server.
