### ISSUE TITLE
search4Recipes cloud function breaks when returning more than one recipe

### ISSUE THREAD

**Issue by armsnyder** [eecs394-spr15/StockMyBar#22]
I've been working on adding functionality for user-selected bar contents, and I'm running into a bug where the cloud function will return an error when it tries to return more than one recipe at a time:

```
{"code":141,"message":"Error: Can't call success/error multiple times\n at Object.success (<anonymous>:99:13)\n at queryJT.find.success (main.js:43:14)\n at Parse.js:2:9371\n at e (Parse.js:2:8151)\n at Parse.js:2:7600\n at Array.forEach (native)\n at Object.x.each.x.forEach [as _arrayEach] (Parse.js:1:661)\n at c.extend.resolve (Parse.js:2:7551)\n at e (Parse.js:2:8286)\n at Parse.js:2:7600"}
```

Furthermore, if no recipes are possible from the user-selected ingredients, we get this error:

```
{"code":141,"message":"success/error was not called"}
```

I'm going to look into this and see if I can fix it, but @missfxhr and @YuxuanHe if you have any ideas, feel free to take a stab at it or comment on this issue.

**Comment by missfxhr** [comment]
The cloud function problem is fixed. It's due to some format reason but anyway the function "search4recipes" should work well now.

**Comment by armsnyder** [comment]
IT WORKS!!! <3
