### ISSUE TITLE
Sort results by percentage of ingredients we have

### ISSUE THREAD

**Issue by armsnyder** [eecs394-spr15/StockMyBar#27]
Currently the results are sorted by number of ingredients we have, but it should sort by percentage of ingredients we have. (I know we're aware of this bug and don't know how to solve it now. Just documenting.)

**Comment by missfxhr** [comment]
I just made breakthrough on cloud function. Now the result will be sorted according to the num of missing items. This new function is named search4recipes2. After this function is tested to be bug free, I will replace the old search4recipes with this new one. So everyone feel free to try the new function.

**Comment by armsnyder** [comment]
I tried replacing search4Recipes with search4Recipes2 and it's not working. The console is logging this error:

```
{"code":141,"message":"TypeError: Object [object Object],[object Object],[object Object],[object Object],[object Object],[object Object] has no method 'get'\n at queryAllIngred.find.success (main.js:125:45)\n at Parse.js:2:9371\n at e (Parse.js:2:8151)\n at Parse.js:2:7600\n at Array.forEach (native)\n at Object.x.each.x.forEach [as _arrayEach] (Parse.js:1:661)\n at c.extend.resolve (Parse.js:2:7551)\n at e (Parse.js:2:8286)\n at Parse.js:2:7600\n at Array.forEach (native)"}
```

**Comment by armsnyder** [comment]
Well that's strange. It's suddenly working now. Did you just make a change?

**Comment by missfxhr** [comment]
Lol that happens, parse server takes time to update its cloud code so that you might just tested old version code.

**Comment by armsnyder** [comment]
There are bugs in the cloud code. Some recipes are showing incorrect ingredients on the results page. For example, "Tequila Sunrise. Have: grenadine. Need: <none>" Furthermore, it is not being sorted by percentage but instead by number of ingredients missing.

**Comment by armsnyder** [comment]
Also, you inadvertently reverted some changes when you merged to master. Please please please avoid doing this, as it won't always be obvious. Deleting other people's code is bad, but doing it by accident and without realizing is worse.

**Comment by missfxhr** [comment]
I am sorry for doing this. I sincerely apologize for it. Since I am not experienced with using github I won't try something I have not used before. So this will not happen again.

I will try to fix the bugs u found in new cloud code.

For the sorting rule, from what I can recall, we agreed to sort recipes by the number of ingreds we missing. However, if most of us think sorting by percentage is better, sure I will modify it. Anyone see this comment can leave a message showing which sorting rule is better in your mind.

**Comment by armsnyder** [comment]
Oh I didn't mean to sound like I was scolding you or anything haha. We're all learning. I just wanted to bring it to your attention. ;)

**Comment by missfxhr** [comment]
Lol it's cool. We are all learning and I should apologize for the mistake I made. I will see whether I can fix the bugs.

**Comment by missfxhr** [comment]
It seems that this bug does not show at my place.
"Tequila Sunrise. Have: grenadine. Need: tequila, orange juice" is what I can see here on my phone.
Could you retest it or provide me more info for this bug?

**Comment by armsnyder** [comment]
Sure. But first I'm trying to manually add back in the code you accidentally took out, and I'm now getting these console logs:
{"code":141,"message":"result2 no!!!"}
{"code":141,"message":"result2 no!!!"}
{"code":141,"message":"result3 no!!!"}
{"code":155,"message":"This application performed 1806 requests within the past minute, and exceeded its request limit. Please retry in one minute or raise your request limit."}
{"code":155,"message":"This application performed 1808 requests within the past minute, and exceeded its request limit. Please retry in one minute or raise your request limit."}
{"code":155,"message":"This application performed 1807 requests within the past minute, and exceeded its request limit. Please retry in one minute or raise your request limit."}
{"code":141,"message":"result3 no!!!"}
{"code":141,"message":"result2 no!!!"}

Do you have any idea why this might be happening? My branch is called [feature/manual-master-revert](https://github.com/eecs394-spr15/StockMyBar/tree/feature/manual-master-revert)

**Comment by armsnyder** [comment]
Never mind. I found it.

**Comment by missfxhr** [comment]
okay finally I found the cause to the bug which appear when the input is large. The reason is that Parse has a default limit on the number of rows returned to users, which is 100. This limit broke one query(results3) thus the final result is not correct. I set the limit to 1000 and bug seems to be fixed. Therefore, everyone feels free to test it more to see whether this bug really disappeared.
