### ISSUE TITLE
Update Database Format / Contents

### ISSUE THREAD

**Issue by armsnyder** [eecs394-spr15/StockMyBar#32]
We should update our backend database to support the features we will be adding, such as:
- Ease of acquiring an ingredient
- Average price of ingredient
- Quantity and unit of ingredient used in a recipe
- Whether an ingredient is optional or required in a recipe
- Ingredient substitutions in a recipe (ex. Triple Sec OR Cointreau is a common one)
- Multiple versions of a recipe
- Recipe type (ex. liquers, shooters, hot drinks, cocktails)
- Short recipe description
- Recipe directions (if not obvious)
- Recipe difficulty

Most of these already have empty fields in the Parse.com database. Does anyone think some of these are unnecessary or that we may need more?

Also, my thought for enabling ingredient substitutions is that we change the "ingredient" column in the Join_Table to accept a list of pointers instead of just one pointer. Would that mess anyone up?

**Comment by missfxhr** [comment]
I am 80% sure that I could handle this change -- one pointer to a list of pointers.

**Comment by missfxhr** [comment]
I also believe that we could first do things other than this pointer change thing. It should be better to move on to this after we talked about it in during our meeting next week.

**Comment by armsnyder** [comment]
agreed

**Comment by missfxhr** [comment]
but yeah adding more columns for either ingred or recipes is totally cool. It won't cause any problems so that we could do it first.

**Comment by missfxhr** [comment]
I suggest we make the first character of name of each ingred/recipe capitalized so that it would be convenient to sort by name.

**Comment by armsnyder** [comment]
I'm currently adding recipes to our shared google sheets form. https://docs.google.com/a/u.northwestern.edu/spreadsheets/d/18bzxGjJ6jcmse9g6Dyj-YMly0xjb70VKprz67PvYylQ/edit#gid=0
