### ISSUE TITLE
Revise home screen to prompt user to input what they like and what they have

### ISSUE THREAD

**Issue by FrankAvino** [eecs394-spr15/StockMyBar#36]

**Comment by missfxhr** [comment]
I currently saw two buttons on home screen. One goes to 'my preference' and the other  goes to 'my bar'. So what else I need to do with this issue?

**Comment by missfxhr** [comment]
@FrankAvino @friendly-flame could you two help me understand what i need to do for this issue? thanks.

**Comment by FrankAvino** [comment]
I revised the names of the buttons to reflect what they point to, so we should be good now.

**Comment by FrankAvino** [comment]
Each button points to either the ingredients, preferences, or results view.
