### ISSUE TITLE
Let the user view their results upon opening the app without having to add any more ingredients.

### ISSUE THREAD

**Issue by FrankAvino** [eecs394-spr15/StockMyBar#51]

**Comment by FrankAvino** [comment]
Right now, in order to get back a list of recipes, the user has to add at least one more ingredient to their list of ingredients in order for the recipe list to refresh.

**Comment by armsnyder** [comment]
Duplicate issue #43

**Comment by FrankAvino** [comment]
Closed since it's a duplicate.
