### ISSUE TITLE
Results view is buggy - "Tap here to add..." is always visible, and "Pick some ingredient..." appears in each result list item

### ISSUE THREAD

**Issue by armsnyder** [eecs394-spr15/StockMyBar#62]

**Comment by armsnyder** [comment]
@FrankAvino You were working on this, right?

**Comment by FrankAvino** [comment]
Yes. I'll double check this in a bit.

On Sun, Apr 26, 2015 at 9:34 PM, Adam Snyder notifications@github.com
wrote:

> @FrankAvino https://github.com/FrankAvino You were working on this,
> right?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/eecs394-spr15/StockMyBar/issues/62#issuecomment-96478105
> .

## 

Frank Avino
Northwestern University | Class of 2015
McCormick School of Engineering and Applied Science | Computer Science major
Philanthropy Co-Chair | The Delta Chi Fraternity
